name: Deploy All Services

on:
  push:
    branches:
      - main

jobs:
  deploy-homepage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Apply (homepage)
        working-directory: services/homepage/terraform
        run: terraform init && terraform apply -auto-approve
      - name: Setup Ansible
        uses: ansible/ansible-github-actions@v1.0.0
      - name: Run Ansible Playbook (homepage)
        working-directory: services/homepage/ansible
        run: ansible-playbook upload_config.yml

  deploy-mealie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Apply (mealie)
        working-directory: services/mealie/terraform
        run: terraform init && terraform apply -auto-approve
